/**
 * JSON schema and types for the self-hosted profile data format.
 *
 * This defines the shape of the cached profile JSON that the GitHub Actions
 * workflow writes to the `persona-cards` repository. The main profiles.sh app
 * can consume this as an alternative data source.
 */

import type { FullProfile } from "../engine";

// ---------------------------------------------------------------------------
// Self-hosted profile envelope
// ---------------------------------------------------------------------------

/**
 * Envelope wrapping the engine output with metadata about when and how
 * the profile was generated. Written to `profile.json` in the user's
 * `persona-cards` repository.
 */
export interface SelfHostedProfile {
  /** Schema version for forward-compatibility checks. */
  schema_version: "1.0.0";

  /** ISO-8601 timestamp of when this profile was generated. */
  generated_at: string;

  /** GitHub username this profile belongs to. */
  username: string;

  /** The full profile payload from the persona engine. */
  data: FullProfile;
}

// ---------------------------------------------------------------------------
// JSON Schema (draft-07) for validation tooling
// ---------------------------------------------------------------------------

export const SELF_HOSTED_PROFILE_SCHEMA = {
  $schema: "http://json-schema.org/draft-07/schema#",
  title: "SelfHostedProfile",
  description:
    "Cached profiles.sh profile data generated by the persona-cards GitHub Actions workflow.",
  type: "object",
  required: ["schema_version", "generated_at", "username", "data"],
  properties: {
    schema_version: {
      type: "string",
      const: "1.0.0",
      description: "Schema version for forward-compatibility.",
    },
    generated_at: {
      type: "string",
      format: "date-time",
      description: "ISO-8601 timestamp of profile generation.",
    },
    username: {
      type: "string",
      minLength: 1,
      description: "GitHub username.",
    },
    data: {
      type: "object",
      description: "Full profile payload from the persona engine.",
      required: [
        "profile",
        "personas",
        "projects",
        "radar_axes",
        "star_interests",
        "aggregates",
      ],
      properties: {
        profile: {
          type: "object",
          required: [
            "username",
            "display_name",
            "bio",
            "location",
            "email",
            "blog",
            "company",
            "avatar_url",
            "followers",
            "following",
            "public_repos",
            "created_at",
          ],
          properties: {
            username: { type: "string" },
            display_name: { type: "string" },
            bio: { type: "string" },
            location: { type: "string" },
            email: { type: "string" },
            blog: { type: "string" },
            company: { type: "string" },
            avatar_url: { type: "string" },
            followers: { type: "number" },
            following: { type: "number" },
            public_repos: { type: "number" },
            created_at: { type: "string" },
          },
        },
        personas: {
          type: "array",
          items: { type: "object" },
          description: "Active persona cards.",
        },
        projects: {
          type: "array",
          items: { type: "object" },
          description: "Project cards mapped to persona domains.",
        },
        radar_axes: {
          type: "array",
          items: {
            type: "object",
            required: ["label", "value", "color", "domain", "sort_order"],
            properties: {
              label: { type: "string" },
              value: { type: "number" },
              color: { type: "string" },
              domain: { type: "string" },
              sort_order: { type: "number" },
            },
          },
          description: "Radar chart axes.",
        },
        star_interests: {
          type: "array",
          items: { type: "object" },
          description: "Star interest clusters.",
        },
        aggregates: {
          type: "array",
          items: { type: "object" },
          description: "Top-10 aggregate charts.",
        },
      },
    },
  },
  additionalProperties: false,
} as const;
