import type { APIRoute } from "astro";

function parseJson(val: unknown): any {
  if (typeof val === "string") {
    try { return JSON.parse(val); } catch { return val; }
  }
  return val;
}

export const GET: APIRoute = async ({ params, locals }) => {
  const username = params.username?.toLowerCase();
  if (!username) return new Response("Missing username", { status: 400 });

  const env = (locals as any).runtime.env as Env;

  const profile = await env.DB.prepare("SELECT * FROM profiles WHERE username = ?")
    .bind(username).first();
  if (!profile) return new Response("Not found", { status: 404 });

  const [personas, projects, radar, interests] = await Promise.all([
    env.DB.prepare("SELECT * FROM personas WHERE username = ? ORDER BY sort_order ASC").bind(username).all(),
    env.DB.prepare("SELECT * FROM projects WHERE username = ? ORDER BY sort_order ASC").bind(username).all(),
    env.DB.prepare("SELECT * FROM radar_axes WHERE username = ? ORDER BY sort_order ASC").bind(username).all(),
    env.DB.prepare("SELECT * FROM star_interests WHERE username = ? ORDER BY sort_order ASC").bind(username).all(),
  ]);

  const lines: string[] = [];
  const name = profile.display_name || username;

  lines.push(`# ${name} — profiles.sh`);
  lines.push("");
  if (profile.bio) lines.push(`> ${profile.bio}`);
  lines.push("");

  const meta: string[] = [];
  if (profile.location) meta.push(profile.location as string);
  if (profile.public_repos) meta.push(`${profile.public_repos} repos`);
  if (profile.followers) meta.push(`${profile.followers} followers`);
  if (meta.length) lines.push(meta.join(" · "));
  lines.push("");

  // Radar
  if (radar.results.length > 0) {
    lines.push("## Skill Radar");
    lines.push("");
    lines.push("| Domain | Score |");
    lines.push("|--------|------:|");
    for (const r of radar.results as any[]) {
      const bar = "█".repeat(Math.round(r.value / 5));
      lines.push(`| ${r.label} | ${bar} ${r.value} |`);
    }
    lines.push("");
  }

  // Personas
  if (personas.results.length > 0) {
    lines.push("## Personas");
    lines.push("");
    for (const p of personas.results as any[]) {
      lines.push(`### ${p.icon || ""} ${p.title}`);
      if (p.tagline) lines.push(`*"${p.tagline}"*`);
      if (p.experience_label) lines.push(`${p.experience_label} · ${p.years_active || ""}`);
      lines.push("");

      const stats = parseJson(p.stats) as any[];
      if (stats?.length) {
        for (const s of stats) {
          const [label, value] = Array.isArray(s) ? s : [s.label, s.value];
          lines.push(`- **${label}**: ${value}`);
        }
        lines.push("");
      }

      const stack = parseJson(p.stack) as string[];
      if (stack?.length) {
        lines.push(`**Stack**: ${stack.join(", ")}`);
        lines.push("");
      }

      const details = parseJson(p.details) as string[];
      if (details?.length) {
        lines.push("**Field Notes**:");
        for (const d of details) lines.push(`- ${d}`);
        lines.push("");
      }

      const employers = parseJson(p.employers) as string[];
      if (employers?.length) {
        lines.push(`**Employers**: ${employers.join(" · ")}`);
        lines.push("");
      }
    }
  }

  // Star Interests
  if (interests.results.length > 0) {
    lines.push("## Star Interests");
    lines.push("");
    for (const i of interests.results as any[]) {
      lines.push(`- **${i.label}** (${i.count}): ${i.examples || ""}`);
    }
    lines.push("");
  }

  // Projects
  if (projects.results.length > 0) {
    lines.push("## Featured Projects");
    lines.push("");
    for (const p of projects.results as any[]) {
      const tech = parseJson(p.tech) as string[];
      lines.push(`### ${p.name}`);
      if (p.description) lines.push(p.description);
      if (tech?.length) lines.push(`**Tech**: ${tech.join(", ")}`);
      if (p.url) lines.push(`[${p.url.replace(/^https?:\/\//, "")}](${p.url})`);
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("*Generated by [profiles.sh](https://profiles.sh) from public GitHub data*");

  return new Response(lines.join("\n"), {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="${username}-profiles.md"`,
    },
  });
};
